# Generated by Django 3.2.7 on 2022-05-10 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genres',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
